### ISSUE TITLE
Please add preview

### ISSUE THREAD

**Issue by DenisIzmaylov** [jondot/awesome-react-native#36]
Hello! Most components has a preview ([example](https://github.com/leecade/react-native-swiper)).
It would be useful to add those previews to current components list and a require a preview on each pull request.
Thanks! :)

**Comment by jondot** [comment]
You are right. I guess we should start working on that, perhaps a format similar to https://github.com/cjwirth/awesome-ios-ui just for the components section?

**Comment by DenisIzmaylov** [comment]
Yeah, looks good

**Comment by jhabdas** [comment]
Seems like these previews could be changing a lot uncontrollably by the maintainers, and therefore should probably not be maintained in a centralized location. The repos linked themselves should contain the updates, so as not to create a maintenance burden - not to mentioned a smörgåsbord of dizzying movement. I feel adding an [NPM downloads count shield](https://img.shields.io/npm/dm/localeval.svg) would hold much more value during comparisons. Also, not everything animates or has a screenshot.

**Comment by TheGermanGuy** [comment]
As an individual with a slow internet connection, I wouldn't recommend this.

**Comment by jondot** [comment]
I would be happy to push a good solution here. I'm guessing the intent is to provide some kind of preview or a way to evaluate how a component looks without really navigating there.

At first, I've added npm and tried other shields, and like @TheMarsGuy is saying, it killed my page load - which is why I've opted to have a process to update stars statically on the page (which I run every now and then).

For something to work, it would have to be considerate at the user's internet connection (having there's hundreds of links here, even my 100M/s connection was having a rough time).

For lack of a better option I'll close this issue, but anyone: feel free to reopen if you have an idea that I could go for.

**Comment by brillout** [comment]
I don't think there is a good way with GitHub only. Instead I've build a frontend that can show the readme (which most of the time includes a preview) for [brillout/awesome-react-components](https://github.com/brillout/awesome-react-components): [devarchy.com/react-components](http://devarchy.com/react-components)
