### ISSUE TITLE
distinguish newly added content

### ISSUE THREAD

**Issue by tsvetann** [jondot/awesome-react-native#89]
The list is growing. It would be very helpful imo to add a special symbol/badge to easily outline the newly added content.

**Comment by jondot** [comment]
I'll be working on that, I have some ideas for how to do this.

**Comment by jondot** [comment]
So this effort have resulted in `jill` (the tool I'm using to maintain this list) getting a new freshness feature [here](https://github.com/jondot/jill/commit/5b929ec453eebe1b62e31f2da910c01d652dda12). It is based on git blame and finding fresh commits.

It turns out, that unless I process entries for the very recent week, almost all entires are marked as fresh (I've tried last two weeks, last month).

I then dawned on me that the React Native ecosystem is growing every day, and this list as well. There's too much additions every week for us to be able to mark what's new and what's not.

So, in closing - once this becomes relevant I'll be activating the freshness feature. But for now let's close this. Please feel free to reopen if you have a better idea for automatically marking freshness.
